dependencies:
  flutter:
    sdk: flutter
  async: ^2.12.0  # Update to the latest version
  boolean_selector: ^2.1.2  # Update to the latest version
  characters: ^1.4.0  # Update to the latest version
  clock: ^1.1.2  # Update to the latest version
  collection: ^1.19.1  # Update to the latest version
  fake_async: ^1.3.2  # Update to the latest version
  leak_tracker: ^10.0.8  # Update to the latest version
  leak_tracker_flutter_testing: ^3.0.9  # Update to the latest version
  matcher: ^0.12.17  # Update to the latest version
  material_color_utilities: ^0.12.0  # Update to the latest version
  meta: ^1.16.0  # Update to the latest version
  path: ^1.9.1  # Update to the latest version
  source_span: ^1.10.1  # Update to the latest version
  stack_trace: ^1.12.1  # Update to the latest version
  stream_channel: ^2.1.4  # Update to the latest version
  string_scanner: ^1.4.1  # Update to the latest version
  term_glyph: ^1.2.2  # Update to the latest version
  test_api: ^0.7.4  # Update to the latest version
  vm_service: ^15.0.0  # Update to the latest version
